import Head from "next/head";
import Image from "next/image";
import Carousel from "../components/Carousel";
import NewsLetter from "../components/NewsLetter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Anchor | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Carousel />
      <header className="text-light text-center container pt-3">
        <h2 className="h2 text-primary"> Welcome To The Anchor Digbeth </h2>
        <p>
          The Anchor, as it is now known &#40;we dropped the
          &#8216;Inn&#8217;&#41; is still a free house so we are free to present
          you with the best and more interesting products available. We
          don&apos;t intend to re-invent the wheel, our aim is simply to provide
          a friendly space for everyone to enjoy great beer, wine, coffee,
          Cocktails and spirits with great service. Simple.
        </p>
      </header>
      <NewsLetter />
    </div>
  );
}
