import Head from "next/head";
import Image from "next/image";
import Carousel from "../components/Carousel";
import NewsLetter from "../components/NewsLetter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Anchor | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Carousel />
      <header className="text-light text-center">
        <div className="container pt-3">
          <h2 className="h2 text-primary"> Welcome To The Anchor Digbeth </h2>
          <p> This is the first page of the Anchor Digbeth website </p>
        </div>
        <div className="container">
          <p className="text-light">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi
            suscipit aut accusamus vero ad voluptates necessitatibus, id fuga
            alias nesciunt recusandae similique ipsa sit labore, aspernatur
            dicta veniam adipisci qui? Lorem ipsum dolor, sit amet consectetur
            adipisicing elit. Cupiditate, eum voluptatibus a tempore iusto
            sapiente officiis nostrum earum repellat fuga qui eligendi. Amet ut
            deleniti voluptas eligendi, aut atque nam. Lorem ipsum, dolor sit
            amet consectetur adipisicing elit. Debitis reprehenderit error earum
            architecto ducimus reiciendis! Temporibus alias quam quas a animi
            sed optio cum, eum sint? Neque amet quia maxime!
          </p>
        </div>
      </header>
      <NewsLetter />
    </div>
  );
}
